name: Deploy Storybook to GitHub Pages

# This workflow automatically builds and deploys Storybook to GitHub Pages
# Triggers:
# - When pushing to main branch
# - When a pull request to main branch is merged
on:
  push:
    branches: 
      - "main"  # Triggers on the main branch
  pull_request:
    types: [closed]
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Only proceed when directly pushing to main branch or when PRs are actually merged
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Persist GitHub credentials for deployment

      # Use Node.js 20 LTS
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook  # Generates static files in storybook-static folder
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static  # Directory containing the static build output
          branch: gh-pages          # Branch to deploy to (GitHub Pages reads from this branch)
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

      - name: Deployment summary
        run: |
          echo "## ✅ Storybook Deployed Successfully" >> $GITHUB_STEP_SUMMARY
          echo "Storybook has been deployed to GitHub Pages." >> $GITHUB_STEP_SUMMARY
          echo "You can view it at: https://engr-lukman.github.io/npm-packages/" >> $GITHUB_STEP_SUMMARY