name: Publish Random String Generator Package

on:
  push:
    branches: 
      - "main"  # Triggers on the main branch
    paths:
      - 'src/random-string-generator/package.json'
  pull_request:
    types: [closed]
    branches:
      - "main"
    paths:
      - 'src/random-string-generator/package.json'

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: https://registry.npmjs.org

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_PUBLISH_TOKEN }}