name: Publish Random String Generator Package

# This workflow automatically publishes the Random String Generator package to npmjs.com
# Triggers:
# - When pushing to main branch with changes to random-string-generator/package.json
# - When a pull request to main branch is merged with changes to random-string-generator/package.json
on:
  push:
    branches: 
      - "main"  # Triggers on the main branch
    paths:
      - 'src/random-string-generator/package.json'
  pull_request:
    types: [closed]
    branches:
      - "main"
    paths:
      - 'src/random-string-generator/package.json'

jobs:
  # First job: Check if the package version has been updated
  check-version-change:
    runs-on: ubuntu-latest
    # Only proceed when directly pushing to main branch or when PRs are actually merged
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    outputs:
      version_changed: ${{ steps.check.outputs.version_changed }}
      current_version: ${{ steps.check.outputs.current_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch last 2 commits to compare versions

      - name: Check if version changed
        id: check
        run: |
          # For pull requests, compare base and head commits
          # For direct pushes, compare with the previous commit
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git fetch origin ${{ github.base_ref }} --depth=1
            PREVIOUS_COMMIT=$(git rev-parse FETCH_HEAD)
            CURRENT_COMMIT=${{ github.sha }}
          else
            PREVIOUS_COMMIT=$(git rev-parse HEAD^1)
            CURRENT_COMMIT=$(git rev-parse HEAD)
          fi
          
          # Extract and compare package versions between commits
          PREVIOUS_VERSION=$(git show $PREVIOUS_COMMIT:src/random-string-generator/package.json | grep '"version":' | cut -d '"' -f 4)
          CURRENT_VERSION=$(git show $CURRENT_COMMIT:src/random-string-generator/package.json | grep '"version":' | cut -d '"' -f 4)
          
          echo "Previous version: $PREVIOUS_VERSION"
          echo "Current version: $CURRENT_VERSION"
          
          # Set the current version as output for use in summary
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
          # Determine whether to publish based on version change
          if [ "$PREVIOUS_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Package version updated from $PREVIOUS_VERSION to $CURRENT_VERSION. Will publish."
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "Package version unchanged ($CURRENT_VERSION). Skipping publish."
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Summary when version unchanged
        if: steps.check.outputs.version_changed == 'false'
        run: |
          echo "## ⚠️ Publish Skipped" >> $GITHUB_STEP_SUMMARY
          echo "Package version was not changed in this commit. Publishing was skipped." >> $GITHUB_STEP_SUMMARY

  # Second job: Build and publish the package to npmjs.com
  build-and-publish:
    runs-on: ubuntu-latest
    needs: check-version-change
    # Only publish if the version was actually changed
    if: needs.check-version-change.outputs.version_changed == 'true'
    permissions:
      contents: read  # Required to check out the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install package dependencies
        working-directory: ./src/random-string-generator
        run: npm install

      - name: Build package
        working-directory: ./src/random-string-generator
        run: npm run build
        
      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_PUBLISH_TOKEN }}
          
      - name: Verify npm account and create scope if needed
        run: |
          echo "Verifying npm user..."
          npm whoami || echo "Not logged in, using token authentication"
          
          # Don't try to create org if it will fail, just proceed with publish
          echo "Will publish using configured authentication"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_PUBLISH_TOKEN }}

      - name: Publish package to npmjs.com
        working-directory: ./src/random-string-generator
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_PUBLISH_TOKEN }}

      - name: Successfully published
        run: |
          echo "## ✅ Package Published Successfully" >> $GITHUB_STEP_SUMMARY
          echo "Random String Generator package v${{ needs.check-version-change.outputs.current_version }} has been published to npmjs.com." >> $GITHUB_STEP_SUMMARY
          echo "Package URL: https://www.npmjs.com/package/@engr-lukman/random-string-generator" >> $GITHUB_STEP_SUMMARY